version: '2.1'

services:
    postgresql:
        restart: always
        image: postgis/postgis:latest
        volumes:
            - psql-vol:/var/lib/postgresql/data
            - ./assets/build/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
        ports:
            - 5432:5432
        environment:
            - TENDENCI_USER=${POSTGRES_USER:-tendenci-usr}
            - TENDENCI_DB=${POSTGRES_DB:-tendenci}
            - TENDENCI_PASS=${POSTGRES_PASSWORD:-mycomplexpassword}
            - POSTGRES_PASSWORD=${POSTGRES_SUPERUSER_PASSWORD:-mycomplexpassword}
        healthcheck:
            test: ["CMD", "pg_isready", "-h", "localhost", "-d", "${POSTGRES_DB:-tendenci}", "-U", "${POSTGRES_USER:-tendenci-usr}", "-p", "5432"]
            interval: 20s
            timeout: 5s
            retries: 5


    tendenci:
        restart: always
        image: tendenci:latest
        depends_on: 
            postgresql:
                condition: service_healthy
        volumes:
            - logs-vol:/var/log/mysite
            - root-vol:/home/tendenci/install/mysite

        ports:
            - 6080:8000
        environment:
            # Postgresql setup
            - DB_USER=${POSTGRES_USER:-tendenci-usr}
            - DB_NAME=${POSTGRES_DB:-tendenci}
            - DB_PASS=${POSTGRES_PASSWORD:-mycomplexpassword}
            - DB_HOST=${DB_HOST:-postgresql}
            - DB_PORT=${DB_PORT:-5432} 

            # Superuser setup
            - ADMIN_USER=${ADMIN_USER:-admin}
            - ADMIN_MAIL=${ADMIN_MAIL:-admin@example.com}
            - ADMIN_PASS=${ADMIN_PASS:-password}
            - SITE_URL=${SITE_URL:-HTTP://myurl.com}
            - TIME_ZONE=${TIME_ZONE:-GMT+0}

volumes:
    root-vol:
    logs-vol:
    psql-vol:
